language: python

python:
- '3.5'

matrix:
  include:
    - python: 3.9-dev
      dist: xenial


branches:
  only:
  - master
  - /^_gitz_stripe_.*$/


install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt

script:
- flake8
- pytest
