language: python

python:
- '3.4'
- '3.8'

branches:
  only:
  - master
  - /^_gitz_stripe_.*$/


install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt

script:
- flake8
- pytest
